### ISSUE TITLE
Adição dos demais membros

### ISSUE THREAD

**Issue by vinicius3w** [IF977/5theWin#1]
Adicionar os demais membros do time no repositório bem como no Time criado na organização do GitHub.

**Comment by emm2** [comment]
Os membros do time ainda não estão na organização:
@tuxao
@iillx
@marciodeaquino
Eu achei que, como líder, eu poderia adicionar à organização e, consequentemente, ao time/repositório.

**Comment by vinicius3w** [comment]
adicionar à organização não pode, mas pode adicionar ao repo.
Convite enviados para adição à organização e ao Time.
