### ISSUE TITLE
Criar Labels

### ISSUE THREAD

**Issue by mpocin** [IF977/5theWin#3]
Criar labels de acordo com a especificação dada na monitoria sobre Git & Github.

**Comment by emm2** [comment]
Eu não encontrei o slide da monitoria com as labels, mas achei um issue de uma turma passada e preenchi as labels.
Caso haja alguma faltante ou errada, favor localizar o slide para que haja o preenchimento adequado.

**Comment by mpocin** [comment]
o slide está no slack e foi adicionado dia 30 de agosto, favor procurar e
verificar preenchimento correto.
^^

**Comment by emm2** [comment]
As labels foram criadas. Favor conferir para fechar o issue.

**Comment by mpocin** [comment]
para mim as cores não estão com o descrito no slide, mas pode ser a tela do
computador q estou usando
para checar:
doc = azul
review = lilás
rejected = amarelo
bug = vermelho
feature = laranja
accepted = verde

## 

MSc Candidate in Computer Science at CIn/UFPE

"Quem forma se forma ou re-forma ao formar, e quem é formado forma-se ao
ser formado." - Paulo Freire

**Comment by emm2** [comment]
Tentei usar umas cores mais definidas para doc, rejected, bug e feature (eu tinha colocado as cores que estavam na paleta do GitHub)
Mudei o review de roxo para lilás.
Favor confirmar para eu colocar como "Accepted"

**Comment by mpocin** [comment]
perfeito! ^^
