### ISSUE TITLE
Criar Milestone para iteração 0

### ISSUE THREAD

**Issue by mpocin** [IF977/5theWin#4]
Criar milestone para iteração 0

**Comment by emm2** [comment]
O Milestone, no caso, seria tudo o que pretendemos terminar até o final da iteração 0?

Isso deve ser colocado no README ou publicado em outro local?

**Comment by mpocin** [comment]
tb, mas o milestone refere-se a uma opcao no github (issues -> milestone)
vc podem criar as issues e atribuir a um milestone.

**Comment by emm2** [comment]
Milestone criado.
